server:
  port: 8000

spring:
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.33.10:3306/wemall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'