server:
  port: 88
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      server:
        webmvc:
          routes:
            - id: after_route
              uri: https://www.baidu.com
              predicates:
                - Query=url, baidu
#暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *