server:
  port: 88
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: product-route
              uri: lb://product
              predicates:
                - Path=/api/product/**
              filters:
                - StripPrefix=2 # 去掉前缀 /api/product/，拼接到 uri 的 lb://product 后面
            - id: coupon-route
              uri: lb://coupon
              predicates:
                - Path=/api/coupon/**
              filters:
                - StripPrefix=2
            - id: member-route
              uri: lb://member
              predicates:
                - Path=/api/member/**
              filters:
                - StripPrefix=2
            - id: order-route
              uri: lb://order
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=2
            - id: ware-route
              uri: lb://ware
              predicates:
                - Path=/api/ware/**
              filters:
                - StripPrefix=2